title: guide.biohackrxiv.org
remote_theme: jekyll-theme-minimal
aux_links:
  "BioHackrXiv": "https://biohackrxiv.org/"
description: "Guidelines for BioHackrXiv, an OSF preprint server for BioHackathon-like events in Life Sciences"

theme: jekyll-theme-minimal